services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: RASPLUS
      MYSQL_USER: over
      MYSQL_PASSWORD: senha123
    volumes:
      - mysql_data_container:/var/lib/mysql
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data

volumes:
  mysql_data_container:
  redis_data_container:
